#!/bin/sh

mkdir -p opk
cp ./ngpcemu opk/ngpcemu
cp ./ngpcemu.png opk/icon.png
cp ./docs/license opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=NGPCEMU
Comment=Neo Geo Pocket emulator
Exec=ngpcemu %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk ngpcemu_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
