#!/bin/sh

mkdir -p ipkg/home/retrofw/emus/ngpcemu
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/emulators
cp ./ngp.elf ipkg/home/retrofw/emus/ngpcemu/ngpcemu
cp ./ngpcemu.png ipkg/home/retrofw/emus/ngpcemu/ngpcemu.png

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: ngpcemu
Version: 20190315
Description: NGPC emulator
Section: emus
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/ngpcemu
Depends:
Source: https://github.com/gameblabla/ngpcemu' > control

print '2.0' > debian-binary

print 'title=NGPCEmu
description=Neo geo pocket Emulator
exec=/home/retrofw/emus/ngpcemu/ngpcemu
clock=600
selectordir=/home/retrofw/roms
selectorfilter=.bin,.ngp,.ngc,.ngpc' > home/retrofw/apps/gmenu2x/sections/emulators/ngpcemu

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../ngpcemu.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
